.setup_python_env: &setup_python_env
    before_script:
        - eval "$(micromamba shell hook --shell=bash)"
        - micromamba activate
        - micromamba install -n base --yes --file environment.yml
        - micromamba install -n base -c conda-forge --yes git git-lfs
        - git config --global --add safe.directory $(pwd)
        - pre-commit install

format_and_lint:
    stage: test
    image: mambaorg/micromamba:0.25.1
    <<: *setup_python_env
    script:
        - pre-commit run --hook-stage manual --all-files
        - git fetch
        - ./check_commit_msgs.sh -c "remotes/origin/${CI_COMMIT_BRANCH}" -m "remotes/origin/${CI_DEFAULT_BRANCH}"
    rules:
        - if: $CI_COMMIT_TAG
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
        - when: always
