tag_version:
    stage: release
    image: node:17-slim
    before_script:
        - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates git-lfs
    script:
        - npm install @semantic-release/gitlab
        - npm i --save-dev conventional-changelog-conventionalcommits
        - npx semantic-release --branches $CI_DEFAULT_BRANCH
    rules:
        - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
