name: data-science-project-template
channels:
    - conda-forge
dependencies:
    - black=23.1.0
    - cookiecutter=2.1.1
    - pre-commit=3.0.4
    - pylint=2.16.1
    - pytest=7.2.1
    - pytest=7.2.1
    - python=3.10.9
    - ruff=0.1.4
