name: data-science-project-template
channels:
    - conda-forge
dependencies:
    - black=24.4.2
    - python=3.10.9
    - pre-commit=3.7.1
    - pylint=3.2.5
    - pytest=7.2.1
    - cookiecutter=2.1.1
    - pytest=7.2.1
