name: '{{cookiecutter.env_name}}'
channels:
    - conda-forge
dependencies:
    - black=24.4.2
    - nbqa=1.8.5
    {%- if cookiecutter.install_jupyter == 'yes' %}
    - jupyter=1.0.0
    {%- endif %}
    - python=3.10.9
    - pre-commit=3.7.1
    - pylint=3.2.5
