name: '{{cookiecutter.env_name}}'
channels:
    - conda-forge
dependencies:
    - black=22.3.0
    - boto3=1.24.28
    - dvc-s3=2.21.0
    - mlflow=2.2.1
    - nbqa=1.2.3
    - ipykernel=6.9.1
    - jupyter=1.0.0
    - python=3.9.7
    - pre-commit=2.18.1
    - pylint=2.12.2
