name: '{{cookiecutter.env_name}}'
channels:
    - conda-forge
dependencies:
    - black=22.3.0
    - nbqa=1.2.3
    {%- if cookiecutter.install_jupyter == 'yes' %}
    - jupyter=1.0.0
    {%- endif %}
    - python=3.9.7
    - pre-commit=2.18.1
    - pylint=2.12.2
