[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

{% if cookiecutter.linter_name == "pylint" %}
[tool.isort]
profile = 'black'
line_length = 100
{% endif %}
