# This is a basic workflow to help you get started with Actions
name: test

# Controls when the workflow will run
on:
    # Triggers the workflow on pull request to the main branch
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    run_pylint:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: setup environment
              uses: mamba-org/provision-with-micromamba@main
              with:
                  environment-file: environment.yaml
            # Runs a set of commands using the runners shell
            - name: activate environment
              shell: bash -l {0}
              run: micromamba activate data-science-project-template
            - name: configure git
              shell: bash -l {0}
              run: |
                  git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git config --global user.name github-actions[bot]
            - name: pytest
              shell: bash -l {0}
              run: pytest tests/
