name: semantic-release

# trigger a release of a new version if commits are added to the default branch (e.g., main)
on:
    push:
        branches:
            - 'main'

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    tag_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - run: npm install semantic-release@24.0.0 conventional-changelog-conventionalcommits@8.0.0
            - run: npx semantic-release
