name: semantic-release

# trigger a release of a new version if commits are added to the default branch (e.g., main)
on:
    push:
        branches:
            - 'main'

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    tag_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - run: npm install semantic-release conventional-changelog-conventionalcommits
            - run: npx semantic-release
